### ISSUE TITLE
Function window.refreshData is not a function: Error

### ISSUE THREAD

**Issue by AuroraBee** [ottomated/turtle-gambit#7]
TypeError: window.refreshData is not a function
![image](https://user-images.githubusercontent.com/68081524/103365096-955c5f80-4abf-11eb-86b1-b7a0988f64d2.png)
![image](https://user-images.githubusercontent.com/68081524/103365104-9c836d80-4abf-11eb-8ddc-323d41a50652.png)

**Comment by derrickmehaffy** [comment]
Copying my comment from the old issue: 

> @Rick1029 I have an open fork that I can take some PRs on, though undecided if I want to act as a core maintainer. If someone else wants to take maintainership it might be better.

https://github.com/derrickmehaffy/turtle-gambit

**Comment by Myoozik** [comment]
I have found a way to remedy the problem that you can see below.

> TypeError: window.refreshData is not a function
> ![image](https://user-images.githubusercontent.com/68081524/103365096-955c5f80-4abf-11eb-86b1-b7a0988f64d2.png)

When running the command "yarn dev" in ./turtle-gambit-master/ with the frontend also running (use command "yarn dev' as well in ./turtle-gambit-master/frontend/ ) a popup application window will appear. It will load the frontend and if no turtles are connected the screen it will stay blank. If you try to then access https://localhost:3000 in a browser it will return an error because the frontend is not loaded in a [Carlo](https://github.com/GoogleChromeLabs/carlo) application instance where the exposed function refreshWindow() is accessible to ./turtle-gambit-master/frontend/pages/index.ts.

Below: Code snippet of the exposed carlo window refreshWindow() function.
>![image](https://user-images.githubusercontent.com/43874526/103362846-6832a000-4b05-11eb-9faf-74bf91aa32d9.png)

In order to get turtles connected to the backend/frontend interface via WS I have used [ngrok](https://dashboard.ngrok.com/get-started/setup) a proxy/tunneling software that Ottomated used in his streams.

To use ngrok: 

1.  Download ngrok from https://dashboard.ngrok.com/get-started/setup and signup.
2.  Once ngrok is setup, run this command "ngrok http (PORT)" where the port number is the one being used in ./turtle-gambit-master/src/index.ts line 9.
   ![image](https://user-images.githubusercontent.com/43874526/103396482-568dde80-4b7f-11eb-883b-0d06a6a5916e.png)
3.  In ./turtle-gambit-master/turtle/startup.lua edit where it says >http.websocket("(ADDRESS)")
![image](https://user-images.githubusercontent.com/43874526/103396504-76bd9d80-4b7f-11eb-93a4-a009148fd095.png)

      to the URL that ngrok gives you upon executing the aforementioned command
  ![image](https://user-images.githubusercontent.com/43874526/103396763-b6d15000-4b80-11eb-9478-2a608b9750fe.png)
      but changing the protocol from http or https to WS so it'll become ws://2c44c8bc3928.ngrok.io
4.  Save the lua file and copy it into the turtle or put it on pastebin for the turtle to access that way.

**Comment by AuroraBee** [comment]
@Myoozik mind making this easier to understand?
i literally understood half of it, and im still getting the same error, ngrok is set-up and all the files changed accordingly.

**Comment by AuroraBee** [comment]
oh, i am just stupid; duh.
you need to:
1. run "yarn dev" in Turtle-Gambit\frontend\
2. run "yarn dev" in Turtle-Gambit\

step 1. starts the Frontend by itself.
step 2. opens a Chrome window using said Frontend, thus not causing this error.
the rest: install ngrok, do above steps.

**Comment by Myoozik** [comment]
Yes, sorry for my lack of communication.

Step 1: Generates the views (frontend files) that display the turtle interface.
Step 2:  The Frontend is then served in a application instance (something of the sort) where certain functions such as the one causing the error above are not void, accessible to be called.

**Comment by AuroraBee** [comment]
this issue is done, if someone still needs help with this, please make your own issue.

**Comment by watisdatikalikffffali** [comment]
i cant belive you guys are falling for this ngrok is a virus as virus total says

**Comment by AuroraBee** [comment]
Oh Dear...

ngrok is NOT a virus, virustotal most likely says it is BECAUSE it opens a
imperfectly protected http tunnel between a ngrok website with an obscure
address on a port which is usually not for rdp/ssh/http/https.
otherwise: there are plenty alternatives, just search for some open source
ones and check the code yourself if you dont want to risk installing a
"virus"

but i guess you would know something about viruses, having created a password + cookie stealer yourself, watisdakalikffffali.

AND PLEASE: this issue is CLOSED: make your own issue if you have problems!

**Comment by watisdatikalikffffali** [comment]
the first time someone replyed to me on this repository im suprised
